name: pillly
description: "Take your pills on time - a friendly pill reminder app"
publish_to: 'none'

version: 1.0.0+1

homepage: https://github.com/visualcookie/pillly
repository: https://github.com/visualcookie/pillly
issue_tracker: https://github.com/visualcookie/pillly/issues

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  alarm: ^5.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  android_notification_icons: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alarm.mp3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#9B59B6"
  adaptive_icon_foreground: "assets/images/icon.png"

android_notification_icons:
  image_path: "assets/images/icon.png"
  icon_name: "ic_launcher"